---
- name: Create promtail directories
  become: true
  become_method: "{{ promtail_custom_become_method }}"
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default(promtail_owner) }}"
    group: "{{ item.group | default(promtail_group) }}"
    mode: "{{ item.mode | default('0750') }}"
    state: "{{ item.state | default('directory') }}"
  loop: "{{ promtail_directories }}"

- name: Download promtail binary
  become: true
  become_method: "{{ promtail_custom_become_method }}"
  ansible.builtin.get_url:
    url: "{{ promtail_download_url }}"
    dest: "{{ promtail_download_desination }}"
    owner: "{{ promtail_owner }}"
    group: "{{ promtail_group }}"
    mode: '0640'
    force: true

- name: Install promtail package (ferdora)
  become: true
  become_method: "{{ promtail_custom_become_method }}"
  ansible.builtin.package:
    name: "{{ promtail_download_desination }}"
    state: present
  when: ansible_distribution == 'Fedora'

- name: Install promtail package (debian)
  become: true
  become_method: "{{ promtail_custom_become_method }}"
  ansible.builtin.apt:
    deb: "{{ promtail_download_desination }}"
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'


- name: Template promtail file
  become: true
  become_method: "{{ promtail_custom_become_method }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(promtail_owner) }}"
    group: "{{ item.group | default(promtail_group) }}"
    mode: "{{ item.mode | default('0640') }}"
  loop: "{{ promtail_templates }}"
  notify:
    - promtail_need_restart